---
title: "Money_rep"
author: "LAREPsi"
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r pkgs, echo=TRUE, message=FALSE, warning=FALSE}
require(osf)
require(tidyverse)
require(readxl)
require(foreign)
require(DescTools)
require(summarytools)
require(ggplot2)
require(gplots)

```


# Open data set

```{r OPEN, echo=TRUE, message=FALSE}

 dir <- getwd()
 setwd(dir)
  osfr::osf_retrieve_node("48pqu") %>% 
  osfr::osf_ls_files() %>%
  osfr::osf_download(conflicts = "skip")
ds   <- "moneydataABCDEF.xlsx"
Data <- readxl::read_excel(ds)
Data <- Data[2:nrow(Data),]
```

# Problem 1

```{r pr1, echo=TRUE}

#Calculating frequencies 
table_cenario1 <-
  table(c
        (Data$economicam,
          Data$felicidade,
          Data$atratividade_trab)
        ) %>% print()

data.frame(x=Data$economicam,
           y=Data$felicidade,
           z=Data$atratividade_trab)

table_cenario_econ <- table(Data$economicam) %>% print()

table_cenario_felic <- table(Data$felicidade) %>% print()

table_cenario_atrat <- table (Data$atratividade_trab) %>% print()

# Making table with the values (these values should be changed with new data)
table_cenario1_geral <- 
  matrix(c
         (87,25,58,60,69,43),
         nrow = 2, 
         dimnames = list(
           c("Maria", "Carolina"),
           c("Economic Term", "Happiness", "Job atractiviness")
           )
         ) %>% print()


# Here is the chi-square test
# chisq_test_econ
chisq.test(table_cenario_econ)

#chisq_test_felic 
chisq.test(table_cenario_felic)

#chisq_test_atrat
chisq.test(table_cenario_atrat)

chisq.test(table_cenario1_geral)

#Cramer V
CramerV(table_cenario_econ,
        conf.level = 0.95,
        method = c("ncchisqadj"))

CramerV(table_cenario_felic,
        conf.level = 0.95,
        method = c("ncchisqadj"))

CramerV(table_cenario_atrat,
        conf.level = 0.95,
        method = c("ncchisqadj"))

CramerV(table_cenario1_geral,
        conf.level = 0.95,
        method = c("ncchisqadj"))
```

```{r prob1graph, echo=TRUE}

# Making Graph with the values (these percentage values should be changed with new data)
Prob1_data_repli_plot <- 
  data.frame(Emphasis = 
               rep(c("Economic terms", "Happines", "Job Atractiviness"),
                   each = 2),
             Choice = 
               rep(c("Carolina", "Maria")),
             Percentage = c(22,78,51,49,38,62)
             ) %>% print()

Prob1_data_repli_plot <- 
  ggplot(
  data = Prob1_data_repli_plot,
  aes(
    x = Emphasis,
    y = Percentage,
    fill = Choice)
  ) +
  geom_bar(
    stat ="identity",
    position = position_dodge(),
    color="black") +  
    labs(
    title =
      "Money Illusion Brazilian Replication Problem 1 (n = 342)",
    x ="Condition",
    y = element_blank()
    )+ 
  theme(legend.position = c(0.9, 0.85)
        )+
  ylim(0,100)

ggsave("barplotprob1.png", 
       plot = Prob1_data_repli_plot,
       width = 8,
       height = 6,
       dpi = 300)
```

# Problem 2
```{r prob2, echo=TRUE}

# Calculating frequencies  
table_cenario2 <- 
  table(c(Data$`A casa_1`,
          Data$`A casa_2`,
          Data$`A casa_3`)
        ) %>% print()

#House 1 = Andre
table_cenario_andre <- table(c(Data$`A casa_1`)
                             )%>% print()

#House 2 = Bento
table_cenario_bento <- table(c(Data$`A casa_2`)
                             )%>% print()

#House 3 = Marcelo
table_cenario_marcelo <- table(c(Data$`A casa_3`)
                               )%>% print()

#House 1 = Andre
freq(Data$`A casa_1`)
#House 2 = Bento
freq(Data$`A casa_2`)
#House 3 = Marcelo
freq(Data$`A casa_3`)

# Here is the chi-square test
chisq.test(table_cenario_andre)

chisq.test(table_cenario_bento)

chisq.test(table_cenario_marcelo)

# Making table with the values (these values should be changed with new data)
table_cenario2_geral <- 
  matrix(
    c(95,57,117,42,184,43,132,28,109),
    nrow = 3, 
    dimnames = list( 
      c("Andre", "Bento", "Marcelo"),
      c("First Choice", "Second Choice", "Third Choice")
      )
    )
table_cenario2_geral
chisq.test(table_cenario2_geral)
CramerV(table_cenario2_geral,
        conf.level = 0.95,
        method = c("ncchisqadj"))

```

```{r prob2graph, echo=TRUE}

Prob2_data_repli_larepsi <-   data.frame(
    Percentage = c(35,21,43,16,68,16,49,11,41),
    Seller = rep(c(
      "Andre",
      "Bento",
      "Marcelo")),
    Rank = rep(c(
      "First Choice",
      "Second Choice",
      "Third Choice"),
      each=3)
    )
Prob2_data_repli_larepsi <- 
  ggplot(
  data = Prob2_data_repli_larepsi,
  aes(
    x=Rank,
    y=Percentage,
    fill= Seller)) +
  geom_bar (
    stat ="identity",
    position = position_dodge(),
    color = "black") + 
    labs(
      title =
      "Money Illusion Brazilian Replication Problem 2 (n = 269)",
      x ="Rank",
      y = element_blank()
      )+
  theme(
    legend.position =
      c(0.9, 0.8)
    )+
  ylim(0, 100)

ggsave("barplotprob2.png", 
       plot = Prob2_data_repli_larepsi,
       width = 8,
       height = 6,
       dpi = 300)

```

# Problem 3

```{r prob3, echo=TRUE}

# Calculating frequencies 

# Table with all data
table_cenario3 <- 
  table(c(
    Data$poltrona_venda_reais,
    Data$poltrona_compra_reai,
    Data$poltrona_venda_porce,
    Data$Q30)
    ) %>% print()

# Table with 'sell' scenarios 
table_cenario3_venda <-
  table(c(
    Data$poltrona_venda_reais,
    Data$poltrona_venda_porce)
    ) %>% print()


# Table with 'buy' scenarios 
table_cenario3_compra <-
  table(c(
    Data$poltrona_compra_reai,
    Data$Q30)
    ) %>% print()

# Showing frequencies
freq(Data$poltrona_compra_reai)
freq(Data$poltrona_venda_reais)
freq(Data$poltrona_venda_porce)
freq(Data$Q30) # "buy" percentage

# Making tables with the values 
#(these values should be changed according to the new data) 
# and comparing Reals and Percentage in the 'buy' scenario

table_cenario3_compra_comparar <- 
  matrix(c
         (59,68,64,59,9,5),
         nrow = 2,
         dimnames = list( c(
           "Buy Reais",
           "Buy Percentage"),
           c(
             "Less",
             "Same",
             "More")
           )
         )

table_cenario3_compra_comparar

# Making tables with the values
#(these values should be changed according to the new data) 
# and comparing Reals and Percentage in the 'sell' scenario
table_cenario3_venda_comparar <-
  matrix(c
         (18,11,72,75,42,46),
         nrow = 2,
         dimnames = list( c(
           "Sell Reais",
           "Sell Percentage"),
           c(
             "Less",
             "Same",
             "More")
           )
         )

table_cenario3_venda_comparar

# Setting the chi-square tests for all scenarios
# all dataset
chisq.test(table_cenario3) 

# all 'sell' scenarios (reais + percentage)  
chisq.test(table_cenario3_venda)

# all 'buy' scenarios (reais + percentage)
chisq.test(table_cenario3_compra)

# comparing 'buy' scenarios
chisq.test(table_cenario3_compra_comparar)

# comparing 'sell' scenarios
chisq.test(table_cenario3_venda_comparar)

# Making tables with the Reals and Percentages values 
#(these values should be changed according to the new data). 
#There is also a table with all the data. 

# Making table  Real values 
Prob3_data_repli_larepsi_reais <- 
  matrix(c
         (14,54,32,45,48,7),
         nrow = 3,
         dimnames = list( c(
           "Less",
           "Same",
           "More"),
           c(
             "Sell Reais",
             "Buy Reais")
           )
         )

#printing the table 'buy x sell' only real values
Prob3_data_repli_larepsi_reais

# Making table Percentage values
Prob3_data_repli_larepsi_porce <- 
  matrix(c
         (8,57,35,51,45,4),
         nrow = 3, 
         dimnames = 
           list( 
             c("Less",
             "Same",
             "More"),
             c("Sell Percentage",
             "Buy Percentage"
             )))

#printing the table 'buy x sell' only percentage values
Prob3_data_repli_larepsi_porce

# Making table all values
table_cenario3_geral <- 
  t(
    matrix(c(127,29,123,147,14, 88),
           nrow = 2,
           dimnames = 
             list(c("Buy", "Sell"),
                   c("Less", "Same", "More")
                  )
           )
    )

# Printing table all values
table_cenario3_geral

#Comparing cells with chi²
chisq.test(Prob3_data_repli_larepsi_reais) #reals
chisq.test(Prob3_data_repli_larepsi_porce) #percentage
chisq.test(table_cenario3_geral)#all

#Cramer's V for all comparisons
CramerV(
  Prob3_data_repli_larepsi_reais,
  conf.level = 0.95,
  method = c("ncchisqadj")
        )

CramerV(
  Prob3_data_repli_larepsi_porce,
  conf.level = 0.95,
  method = c("ncchisqadj")
        )

CramerV(
  table_cenario3_geral,
  conf.level = 0.95,
  method = c("ncchisqadj")
        )

```

```{r pro3graph, echo=TRUE}
Prob3_data_repli <-
  data.frame(
    Decision = rep(
      c("Buy", "Sell"),
      each = 3),
    Likelihood = rep(
      c("More", "Same", "Less")
                    ),
    Percentage = c(5,47,48, 33,56,11)
            ) %>% print()



Prob3_data_repli<-
  ggplot(
  data = Prob3_data_repli, 
  aes (
    x = Decision,
    y = Percentage,
    fill = factor (
      Likelihood, 
      level = c("More", "Same", "Less")
                  )
      )
      ) +
  geom_bar(
    stat = "identity",
    position = position_dodge(),
    color = "black"
          ) + 
  labs(
    title =
      "Money Illusion Brazilian Replication Problem 3 (n = 264)",
    x ="Decision",
    y = element_blank()
      ) + 
  theme(legend.position = c(0.8,0.8)
        )+
  scale_fill_discrete(name="Likelihood")+
  
  #theme(
  # panel.background = element_rect(fill = "white"))+
  #scale_fill_grey()+
  ylim(0,100)

ggsave("barplotprob3.png", 
       plot = Prob3_data_repli,
       width = 8,
       height = 6,
       dpi = 300)

```

# Problem 4

```{r prob4, echo=TRUE}
# Making the table
table1 <-
  table(c
        (Data$contrato_AB,
          Data$contrato_CD,
          Data$contrato_EF)
        ) %>% print()

# Checking frequencies for each condition
freq(Data$contrato_AB)
freq(Data$contrato_CD)
freq(Data$contrato_EF)

# Here is the chi-square test
chisq_test <- chisq.test(table1)
chisq_test

# Observed data
chisq_test$observed

# Expected data
round(chisq_test$expected,2)

# Pearson Residuals
round(chisq_test$residuals, 3)

#Cramer's V for all scenario
CramerV(
  table1,
  conf.level = 0.95,
  method = c("ncchisqadj")
  )
                 
# Calculating chi-squared for each term

# real terms
tableAB <- 
  t(matrix(c
           (22,50,78,50),
           nrow = 2, 
           dimnames = list( 
             c("AB", "Expected"),
             c("Risky", "Riskless")
             )
           )
    )
print(tableAB)
chisq.test(tableAB)

# nominal terms
tableCD <-
  t(matrix(c
           (27,50,73,50),
           nrow = 2,
           dimnames = list( 
             c("CD", "Expected"),
             c("Risky", "Riskless")
             )
           )
    )
print(tableCD)
chisq.test(tableCD)

# neutral terms
tableEF <- 
  t(matrix(c
           (47,50,53,50),
           nrow = 2,
           dimnames = list( 
             c("EF", "Expected"),
             c("Risky", "Riskless")
             )
           )
    )
print(tableEF)
chisq.test(tableEF)



# comparing real and nominal terms
tableRN <- 
  t(matrix(c
           (22,27,78,73),
           nrow = 2, 
           dimnames = list( 
             c("AB", "CD"),
             c("Risky", "Riskless")
             )
           )
    )
print(tableRN)
chisq.test(tableRN)


```

```{r pro4graph, echo=TRUE}

Prob4_data_repli_plot <- 
  data.frame(
    Emphasis = rep(c
                   ("Real Terms",
                     "Nominal Terms",
                     "Neutral Terms"),
                   each = 2), 
    Choice = rep(c
                 ("Risky",
                   "Riskless")
                 ), 
    Percentage = c(22,78,27,73,47,53)
              ) %>% print()

Prob4_data_repli_plot$Emphasis <-
  factor(Prob4_data_repli_plot$Emphasis, 
                                           levels = c("Real Terms",
                                                      "Nominal Terms",
                                                      "Neutral Terms"))


Prob1_repli_graph_plot <- 
  ggplot(
    data = Prob4_data_repli_plot,
    aes(
      x = Emphasis,
      y = Percentage,
      fill = Choice)
         ) +
  geom_bar(
    stat = "identity",
    position = position_dodge(),
    color = "black") + 
  labs(
    title = 
      "Money Illusion Brazilian Replication Problem 4 (n = 257)",
    x ="Condition",
    y = element_blank()
       )+
  theme(legend.position = c(.92, 0.9)
        ) +
  ylim(0,100)

Prob1_repli_graph_plot

ggsave("barplotprob4.png", 
       plot = Prob1_repli_graph_plot,
       width = 7,
       height = 5,
      dpi = 300)
##############################################################
#### We are proud that you reached the end of our script!! 
#### Congrats ;)
#### If you have any doubt or run into problems with 
#### this script please write to larepsipuc@gmail.com
#############################################################


```


# References

```{r citation, echo=TRUE, message=FALSE, warning=FALSE}
citation()
packages <- c("tidyverse", "osfr", "readxl",
              "dplyr","foreign","DescTools",
              "summarytools", 
              "ggplot2", "gplots")


citation_text <- ""
for (package in packages) {
  package_citation <- capture.output(citation(package))
  citation_text <- paste(citation_text, 
                         paste(package_citation, 
                               collapse = "\n"), 
                         sep = "\n\n")
}

cat(citation_text)

```

# Codebook

```{r codebook}
# Clean objects from the workspace
# Open the ds again
 dir <- getwd()
 setwd(dir)
  osfr::osf_retrieve_node("48pqu") %>% 
  osfr::osf_ls_files() %>%
  osfr::osf_download(conflicts = "skip")
ds   <- "moneydataABCDEF.xlsx"
Data <- readxl::read_excel(ds)
Data <- Data[2:nrow(Data),]

# Check if all chr and num are ok
glimpse(Data)

# If not, fix them
Data$idade <- as.numeric(Data$idade)

# Begin codebook
library(codebookr)
library(haven)
library(dplyr, warn.conflicts = FALSE)
study_codebook <- codebook(Data)
print(study_codebook, "basic_study_codebook.docx")

```
